# Generated by Django 4.1.3 on 2023-11-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onwer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=10)),
                ('nick_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('floor', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('onwer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onwers', to='clinic.onwer')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('pet', models.ManyToManyField(blank=True, related_name='pets', to='clinic.pet')),
                ('veterinarian', models.ManyToManyField(blank=True, related_name='veterinarians', to='clinic.veterinarian')),
            ],
        ),
    ]
