# Generated by Django 4.2.7 on 2024-02-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onwer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Хозяин',
                'verbose_name_plural': 'Хозяева',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=10, verbose_name='Вид')),
                ('breed', models.CharField(max_length=20, verbose_name='Порода')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('nick_name', models.CharField(max_length=10, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст лет')),
                ('weight', models.IntegerField(verbose_name='Вес кг.')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('medical_history', models.TextField(max_length=1000, null=True, unique=True, verbose_name='История болезни')),
                ('slugPet', models.SlugField(max_length=20, null=True, unique=True, verbose_name='Slug')),
                ('onwer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onwers', to='clinic.onwer', verbose_name='Хозяин')),
            ],
            options={
                'verbose_name': 'Питомцы',
                'verbose_name_plural': 'Питомцы',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=15, verbose_name='Специалист')),
                ('firstname', models.CharField(max_length=10, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=20, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=12, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('history', models.TextField(max_length=1000, null=True, unique=True, verbose_name='О докторе')),
                ('certificates', models.CharField(max_length=12, null=True)),
                ('slugVet', models.SlugField(max_length=20, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Ветеринар',
                'verbose_name_plural': 'Ветеринары',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='clinic_vete_id_939c8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('pet', models.ManyToManyField(blank=True, related_name='pets', to='clinic.pet')),
                ('veterinarian', models.ManyToManyField(blank=True, related_name='veterinarians', to='clinic.veterinarian')),
            ],
        ),
        migrations.AddIndex(
            model_name='onwer',
            index=models.Index(fields=['id'], name='clinic_onwe_id_871f67_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['time_create'], name='clinic_pet_time_cr_91cf70_idx'),
        ),
    ]
