# Generated by Django 4.1.3 on 2023-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinarian',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
