# Generated by Django 4.2.7 on 2023-12-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_veterinarian_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='onwer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onwers', to='clinic.onwer'),
        ),
    ]
