# Generated by Django 4.2.7 on 2023-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_pet_onwer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
