# Generated by Django 4.2.7 on 2023-12-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_pet_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='floor',
        ),
    ]
