# Generated by Django 4.2.7 on 2023-12-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_pet_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='image',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
