# Generated by Django 4.2.7 on 2023-12-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_pet_slugpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medical_history',
            field=models.TextField(max_length=1000, null=True, unique=True, verbose_name='История болезни'),
        ),
    ]
