# Generated by Django 4.2.7 on 2023-12-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_veterinarian_slugvet'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinarian',
            name='certificates',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='history',
            field=models.TextField(max_length=1000, null=True, unique=True, verbose_name='О докторе'),
        ),
    ]
