# Generated by Django 4.2.7 on 2023-12-08 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_veterinarian_certificates_veterinarian_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['time_create'], 'verbose_name': 'Питомцы', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(verbose_name='Возраст лет'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=10, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(max_length=12, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nick_name',
            field=models.CharField(max_length=10, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='onwer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onwers', to='clinic.onwer', verbose_name='Хозяин'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='view',
            field=models.CharField(max_length=10, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(verbose_name='Вес кг.'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['time_create'], name='clinic_pet_time_cr_91cf70_idx'),
        ),
    ]
