# Generated by Django 4.2.7 on 2024-01-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_alter_onwer_options_alter_onwer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='veterinarian',
            options={'ordering': ['id'], 'verbose_name': 'Ветеринар', 'verbose_name_plural': 'Ветеринары'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddIndex(
            model_name='veterinarian',
            index=models.Index(fields=['id'], name='clinic_vete_id_939c8e_idx'),
        ),
    ]
