# Generated by Django 4.2.7 on 2024-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_uploadfiles_alter_veterinarian_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='email',
            field=models.EmailField(max_length=20, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='firstname',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='lastname',
            field=models.CharField(max_length=15, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='specialist',
            field=models.CharField(max_length=15, verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='tel',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
