# Generated by Django 4.2.7 on 2024-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_pet_breed_alter_veterinarian_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinarian',
            name='image',
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
