# Generated by Django 4.2.7 on 2024-02-12 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('skidka', models.FloatField(default=1)),
                ('vkorzine', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=12)),
                ('total', models.IntegerField()),
                ('samzakaz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('summa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tovar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Izbran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.tovar')),
            ],
        ),
    ]
